### ISSUE TITLE
[mod] 리뷰 작성뷰 에러 수정

### ISSUE THREAD

**Issue by Dan2dani** [GEON-PPANG/GEON-PPANG-AOS#122]
## What is this issue? 🛠
- 리뷰 작성뷰에서 좋았어요를 선택하고 keyword를 선택한 후 아쉬웠어요를 선택하는 경우 이 전에 선택했던 keyword가 서버에 request 되는 에러를 발견했고 이를 다음과 같이 수정합니다.
리뷰 작성뷰에서 "아쉬웠어요" 선택 시 빈 리스트가 전달되도록 수정
- 리뷰 작성뷰에서 버튼 활성화가 잘못되는 에러를 발견해서 수정합니다.

## Progress 🏃‍♀️
- [x] 리뷰 작성뷰에서 "아쉬웠어요" 선택 시 빈 리스트가 전달되도록 수정
- [x] 버튼 활성화 로직 에러 수정
- [x] livedata -> flow로 migration

**Comment by jooyyoo** [comment]
이다은 멋있네,,
