### ISSUE TITLE
[mod] BreadType, NutrientType DTO 수정 및 로직 수정(마이페이지, 내가 쓴 리뷰, 저장 목록)

### ISSUE THREAD

**Issue by Dan2dani** [GEON-PPANG/GEON-PPANG-AOS#224]
## What is this issue? 🛠
BreadType, NutrientType DTO 수정 및 로직 수정(마이페이지, 내가 쓴 리뷰, 저장 목록)

## Progress 🏃‍♀️
- [ ] BreadType DTO 수정
- [ ] NutrientType DTO 수정
- [ ] 칩 보여주는 부분 chip inflate 하는 방식으로 수정

**Comment by jihyunniiii** [comment]
마이페이지 회원정보 조회 API도 해주시는 건가요?? 제 담당인 줄 알았는데 ㅋ.ㅋ
